exec-once = nm-applet
exec-once = blueman-applet
exec-once = waybar
#exec-once = hyprpaper
exec-once = elephant
#exec-once = walker --gapplication-service
exec-once = swaybg -i /home/amiel/.config/hypr/wallpapers/jap2.jpg -m fill
exec-once = dunst
exec-once = hyprsunset
#exec-once = cclipd -s 2 -t "image/png" -t "image/*" -t "text/plain;charset=utf-8" -t "text/*" -t "*"
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# Start Ollama
exec-once = systemctl --user start ollama || ollama serve
exec-once = hypridle
exec-once = /home/amiel/.config/hypr/scripts/sync-others.sh watch
# Start PicoClaw in background (optional)
exec-once = foot -e sh -c 'picoclaw agent 2>/dev/null'
