-- Generated by nwg-displays, translated to Lua manually

hl.monitor("eDP-1", "1920x1080@60.0", "735x534", 1.25, "bitdepth", 10)
hl.monitor("HDMI-A-1", "1920x1080@144.0", "2271x423", 1.0, "bitdepth", 10)
