# Window rules for wofi launcher
windowrule = match:class ^wofi$, float 1
windowrule = match:class ^wofi$, center 1
windowrule = match:class ^wofi$, size 500 400

# Make GNOME Calculator float instead of tile
windowrule = match:class ^(org\.gnome\.Calculator)$, float 1
windowrule = match:class ^(org\.gnome\.Calculator)$, size 360 630
windowrule = match:class ^(org\.gnome\.Calculator)$, center 1

# Wndow rules for overskride
windowrule = match:class ^io\.github\.kaii_lb\.Overskride$, float 1
windowrule = match:class ^io\.github\.kaii_lb\.Overskride$, center 1
windowrule = match:class ^io\.github\.kaii_lb\.Overskride$, size 500 400



