-- Generated by nwg-displays, translated to Lua manually

hl.workspace_rule(4, "monitor:HDMI-A-1")
hl.workspace_rule(5, "monitor:HDMI-A-1")
hl.workspace_rule(6, "monitor:HDMI-A-1")
hl.workspace_rule(7, "monitor:HDMI-A-1")
hl.workspace_rule(8, "monitor:HDMI-A-1")
hl.workspace_rule(9, "monitor:eDP-1")
hl.workspace_rule(10, "monitor:eDP-1", "default:true")
hl.workspace_rule(3, "monitor:HDMI-A-1")
hl.workspace_rule(2, "monitor:HDMI-A-1")
hl.workspace_rule(1, "monitor:HDMI-A-1", "default:true")
