# -----------------------------
# Input configuration
# -----------------------------

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
   kb_options = altwin:swap_alt_win #eto is used when using the external wireless keyboard(mac mode lang sya nagana so HAHAHA gg), always comment out kung laptop na ung gamit

}

# Touchpad
input:touchpad {
    natural_scroll = true
    tap-to-click = true
    disable_while_typing = true
}
#input:mouse {
#    natural_scroll = true
#}

