# Font
font_family FiraCode Nerd Font
font_size 11.0

# Cursor
cursor_shape block
cursor_blink_interval 0

# Window transparency
background_opacity 0.80
dynamic_background_opacity yes

# Window padding
window_padding_width 8

# Scrollback
scrollback_lines 10000

# Enable ligatures
disable_ligatures never

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Black & White colors
background #000000
foreground #ffffff

selection_background #ffffff
selection_foreground #000000

# Cursor colors
cursor #f5e0dc
cursor_text_color #1e1e2e

